// Depth-tested affine triangles: the same 3D mesh scene without a GPU requirement.
export function createSoftwareRenderer(canvas,THREE){
 const ctx=canvas.getContext('2d',{alpha:false});let W=300,H=200,frame,zbuffer;const vm=new THREE.Matrix4(),cache=new WeakMap();
 function pixels(image){if(cache.has(image))return cache.get(image);if(!image.width||image.complete===false)return null;const c=document.createElement('canvas');c.width=c.height=64;const g=c.getContext('2d');g.drawImage(image,0,0,64,64);const data=g.getImageData(0,0,64,64).data;cache.set(image,data);return data}
 function clip(poly){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ai=a.z<-.04,bi=b.z<-.04;if(ai)out.push(a);if(ai!==bi){const t=(-.04-a.z)/(b.z-a.z);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:-.04,u:a.u+(b.u-a.u)*t,v:a.v+(b.v-a.v)*t})}}return out}
 function triangle(a,b,c,material,shade,f,aspect){const p=v=>({x:W/2+v.x/-v.z*W*f/aspect/2,y:H/2-v.y/-v.z*H*f/2,z:-v.z,u:v.u,v:v.v});a=p(a);b=p(b);c=p(c);
 const den=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(den)<.001)return;const minX=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),maxX=Math.min(W-1,Math.ceil(Math.max(a.x,b.x,c.x))),minY=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),maxY=Math.min(H-1,Math.ceil(Math.max(a.y,b.y,c.y)));if(minX>maxX||minY>maxY)return;
 const image=material.map?.image,tex=image?pixels(image):null,hex=material.color.getHex(),mr=(hex>>16)&255,mg=(hex>>8)&255,mb=hex&255,alpha=material.opacity??1,emission=material.isMeshBasicMaterial?1:shade;
 for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const wa=((b.y-c.y)*(x-c.x)+(c.x-b.x)*(y-c.y))/den,wb=((c.y-a.y)*(x-c.x)+(a.x-c.x)*(y-c.y))/den,wc=1-wa-wb;if(wa<-.0001||wb<-.0001||wc<-.0001)continue;const z=1/(wa/a.z+wb/b.z+wc/c.z),i=y*W+x;if(z>=zbuffer[i])continue;zbuffer[i]=z;const j=i*4;let r=mr*emission,g=mg*emission,bv=mb*emission;
 if(tex){const u=Math.max(0,Math.min(63,Math.floor((wa*a.u+wb*b.u+wc*c.u)*63))),v=Math.max(0,Math.min(63,Math.floor((1-wa*a.v-wb*b.v-wc*c.v)*63))),t=(v*64+u)*4;r=tex[t]*emission*(.65+mr/700);g=tex[t+1]*emission*(.65+mg/700);bv=tex[t+2]*emission*(.65+mb/700)}
 const fog=Math.min(.85,Math.max(0,(z-6)/13));r=r*(1-fog)+23*fog;g=g*(1-fog)+28*fog;bv=bv*(1-fog)+37*fog;frame.data[j]=r*alpha+frame.data[j]*(1-alpha);frame.data[j+1]=g*alpha+frame.data[j+1]*(1-alpha);frame.data[j+2]=bv*alpha+frame.data[j+2]*(1-alpha);frame.data[j+3]=255;
 }}
 return{setPixelRatio(){},setClearColor(){},set outputColorSpace(v){},setSize(w,h){W=Math.min(w,320);H=Math.round(W*h/w);canvas.width=W;canvas.height=H;frame=ctx.createImageData(W,H);zbuffer=new Float32Array(W*H)},render(scene,camera){scene.updateMatrixWorld();camera.updateMatrixWorld();camera.matrixWorldInverse.copy(camera.matrixWorld).invert();zbuffer.fill(Infinity);for(let j=0;j<frame.data.length;j+=4){frame.data[j]=25;frame.data[j+1]=30;frame.data[j+2]=39;frame.data[j+3]=255}const f=1/Math.tan(camera.fov*Math.PI/360);
 scene.traverseVisible(mesh=>{if(!mesh.isMesh)return;const geo=mesh.geometry,attr=geo.attributes.position,uv=geo.attributes.uv,index=geo.index;if(!index)return;const material=Array.isArray(mesh.material)?mesh.material[0]:mesh.material;vm.multiplyMatrices(camera.matrixWorldInverse,mesh.matrixWorld);const m=vm.elements,vs=[];for(let i=0;i<attr.count;i++){const x=attr.getX(i),y=attr.getY(i),z=attr.getZ(i);vs.push({x:m[0]*x+m[4]*y+m[8]*z+m[12],y:m[1]*x+m[5]*y+m[9]*z+m[13],z:m[2]*x+m[6]*y+m[10]*z+m[14],u:uv?.getX(i)||0,v:uv?.getY(i)||0})}
 for(let i=0;i<index.count;i+=3){const a=vs[index.getX(i)],b=vs[index.getX(i+1)],c=vs[index.getX(i+2)],ab={x:b.x-a.x,y:b.y-a.y,z:b.z-a.z},ac={x:c.x-a.x,y:c.y-a.y,z:c.z-a.z},n={x:ab.y*ac.z-ab.z*ac.y,y:ab.z*ac.x-ab.x*ac.z,z:ab.x*ac.y-ab.y*ac.x};if(n.x*a.x+n.y*a.y+n.z*a.z>=0)continue;const poly=clip([a,b,c]);if(poly.length<3)continue;const len=Math.hypot(n.x,n.y,n.z)||1,shade=.75+.23*Math.max(0,(n.y*.8+n.z*.4-n.x*.3)/len);for(let j=1;j<poly.length-1;j++)triangle(poly[0],poly[j],poly[j+1],material,shade,f,camera.aspect)}
 });ctx.putImageData(frame,0,0)}}
}
